version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=5000
    ports:
      - '5000:5000'
    networks:
      - ecommerce-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - ecommerce-network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongo-data:
